### ISSUE TITLE
breakpoints dont work in chromium android webview code

### ISSUE THREAD

**Issue by aabramovsky** [adelphes/android-dev-ext#19]
Hi Dave. 
I am using your androud vscode plugin and it looks very promising. Currently I am trying to debug webview app from chroumium project. I build a debug version of AndroidWebView.apk without optimizations and set up your plugin. It starts activity on the device and shows thread list, but breakpoints show error "breakpoint location is not valid".
Gdb debugger attaches to this process and breakpoints work from command line.

What could be the reason and is it possible to enable breakpoints in vscode?

**Comment by adelphes** [comment]
> Gdb debugger attaches to this process and breakpoints work from command line.
Are you trying to set breakpoints in native code (i.e something other than a Java class) - if so , it's not going to work with my plugin.

The reason is that the Android debugger is implemented using JDWP - this is a protocol that (as far as I know) only works with Java classes. If you need to debug native code, you might be able to setup multiple launch configurations (an android config to launch the app and a gdb config to attach to the native code), but I've never tried it. If that doesn't work, you're probably stuck with the command-line for now.

**Comment by adelphes** [comment]
Closing as this is probably covered by #31
