### ISSUE TITLE
windows 10,breakpoints dont work

### ISSUE THREAD

**Issue by lbhnrg2021** [adelphes/android-dev-ext#24]
windows 10,breakpoints dont work

**Comment by adelphes** [comment]
Since I don;t have a Windows 10 machine, I'll need much more information from you.

- what version of VSCode?
- are you able to set breakpoints in the editor gutter?
- do you try and set the breakpoints before you start debugging or after debugging has started
- where are you setting the breakpoints? In your own source code (java, kotlin, ..?) or in the Android source?
- do the breakpoints get enabled (turn to solid red) when you start debugging
- what happens when a breakpoint is supposed to be hit? Does it just ignore it and continue or stop or something else?

**Comment by cgomezmendez** [comment]
what version of VSCode?
1.25.1
are you able to set breakpoints in the editor gutter?
Yes
do you try and set the breakpoints before you start debugging or after debugging has started
where are you setting the breakpoints? In your own source code (java, kotlin, ..?) or in the Android source?
Before, my code is in kotlin
do the breakpoints get enabled (turn to solid red) when you start debugging
what happens when a breakpoint is supposed to be hit? Does it just ignore it and continue or stop or something else?
Yes they get red
they just get ignored.

**Comment by lbhnrg2021** [comment]
windows are not case sensitive,so
src/debugMain.js
line:614
for (var pkg in this.src_packages.packages) {
            var pkgpath = (pkginfo = this.src_packages.packages[pkg]).package_path;
            pkgpath = pkgpath.toLowerCase();
            srcfolder = srcfolder.toLowerCase();
            if (pkgpath === srcfolder)
                break;
            pkginfo = null;
        }
solved!!!

**Comment by adelphes** [comment]
@lbhnrg2021 that's great. If this fixes the issue, do you want to open a PR and I'll merge it in (so you get the credit).
From your profile, this appears to be your first issue on GitHub - if you need some help to create a PR, let me know.

**Comment by mumin16** [comment]
for (var pkg in this.src_packages.packages) {
var pkgpath = (pkginfo = this.src_packages.packages[pkg]).package_path;
pkgpath = pkgpath.toLowerCase();
srcfolder = srcfolder.toLowerCase();
if (pkgpath === srcfolder)
break;
pkginfo = null;
}


thanks!!!!

**Comment by adelphes** [comment]
this should now be fixed in #55
