### ISSUE TITLE
Launch failed

### ISSUE THREAD

**Issue by Uddhav-Paudel** [adelphes/android-dev-ext#29]
After adding Launch configuration as below

{
    
    "version": "0.2.0",
    "configurations": [
    {
        "type": "android",
        "request": "launch",
        "name": "Launch App",
        "appSrcRoot": "${workspaceRoot}",
        "apkFile": "${workspaceRoot}/build/outputs/apk/android-debug.apk",
        "adbPort": 5037
    }
    ]
}

I faced the following error

Checking build
Warning: Build is not up-to-date. Source files may not match execution when debugging.
Searching for devices...
Found 1 device
Current build already installed
Launching com.dev.test.android/MainActivity on device TA38502I37 [API:23]
Launch failed: Error: Activity class {com.dev.test.android/MainActivity} does not exist.

Please correct me, if I am missing anything?

**Comment by adelphes** [comment]
> Warning: Build is not up-to-date. Source files may not match execution when debugging.

That warning is because you haven't rebuilt your app after changing something in your source files. Rebuild your app (execute `gradlew assembleDebug` in the root of your project folder) and try launching again.

The debugger extracts information about what activity to run from your AndroidManifest.xml file - if you've changed the launch activity and not rebuilt your app, you'll see this error.

**Comment by adelphes** [comment]
This should now be fixed with #72 which loads the manifest directly from the APK.
