### ISSUE TITLE
Launch failed: Cannot read property 'connection' of null

### ISSUE THREAD

**Issue by mccoysc** [adelphes/android-dev-ext#30]
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "android",
            "name": "Android Debug",
            "request": "launch",
            "appSrcRoot": "${workspaceRoot}/app/src/main",
            "apkFile": "${workspaceRoot}/app/build/outputs/apk/debug/app-debug.apk",
            "adbPort": 5037
        }
    ]
}

Checking build
Warning: Build is not up-to-date. Source files may not match execution when debugging.
Searching for devices...
Found 1 device
Current build already installed
Launching js.j2v8/.MainActivity on device emulator-5554 [API:27]
Launch failed: Cannot read property 'connection' of null
Debugger disconnected

**Comment by guobin8205** [comment]
i have same luanch configuration and got same error with you.

**Comment by adelphes** [comment]
There a number of issues relating to the debugger not starting on the emulators.
Often it's because the emulator does not support the APIs the app is relying upon - for example, building an app that uses APIs from Google Play Services and then running it on a non-play-services emulator will cause this.

In any case, viewing logcat on the emulator should show the reason why the debugger disconnects.

Closing until more information is available.
