### ISSUE TITLE
What does the extension do with the APK?

### ISSUE THREAD

**Issue by geajack** [adelphes/android-dev-ext#53]
Typically with my code, I compile the APK, then use `adb push` to send it to `/system/priv-app`. Since I started using this extension I'm having weird behavior, where my changes aren't reflected in the app if I push the APK manually, only if I push it using this extension. So it seems like however the extension is installing the APK is giving it higher priority than the copy in `/system/priv-app`.

What does this extension do with the APK, and how can I remove it from the device?

**Comment by geajack** [comment]
If anyone else has similar trouble, this seemed to do the trick:

1. Use `adb shell` to navigate to navigate to the `/data/data` directory on the device.
2. Use `ls` to list all files, this is a list of installed apps. The names look like Java package paths.
3. Find the one corresponding to your app (I just used a process of "that looks about right", but it'll correspond to the package structure of your code, I assume).
4. Exit the ADB shell and enter `adb uninstall <app>`, where <app> is the name you found in step (3).

**Comment by adelphes** [comment]
Hi @geajack  It's not clear why you are pushing to `/system/priv-app` instead of using `adb install` on the APK. The Android debugger extension pushes the APK to the `/data/local/tmp` folder and then uses the package manager command `'pm install -r <apk>'` to perform the installation.

Using `adb install` and `adb uninstall` is the usual way to update packages on a connected device.
