### ISSUE TITLE
Extract package name from APK during deployment

### ISSUE THREAD

**Issue by adrianstephens** [adelphes/android-dev-ext#72]
The package name passed to am is currently extracted from the AndroidManifest.xml file, but is also embedded in the apk. In our case these do not match (there are some extra .XXX bits added). As a temporary workaround I added 'apkPackage' to the configuration options, but it would be better to read it from the apk.
AAPT can display the package name, and probably everything else you're currently reading from the manifest, but I imagine you'd prefer not to be dependent on that executable. AFAIK the information is stored in an embedded AndroidManifest.xml as a binary XML file within the APK. Not sure if there are js modules that can read that?

**Comment by adelphes** [comment]
Yes, the package name is currently extracted from the manifest because the first versions of the code were created back in the day before manifest merging and package name overriding were a thing.

I agree that reading the value directly from the APK makes sense. Using `aapt` might not be bad if it's included in the basic Android SDK - after all, the extension currently relies upon ADB being present to deploy the app and setup the debugger connection.

I will see if this can be done a bit more reliably, or feel free to submit a PR if you find a solution that works.

**Comment by adelphes** [comment]
Related to #29
